PUT http://127.0.0.1:8000/api/inscriptions/bulletin/1/participant/72 HTTP/1.1
Content-Type: application/json

{
    "prenom": "Participant 22",
    "ages": "1",
    "poids": "1",
    "tailles": "1"
}

// GET http://localhost:8000/api/inscriptions/1 HTTP/1.1
// Content-Type: application/json

// GET  http://localhost:8000/api/dropdown/ages HTTP/1.1
// Content-Type: application/json

// /inscriptions/bulletin/{id}/participant/{id}

// POST  http://127.0.0.1:8000/api/inscriptions HTTP/1.1
// Content-Type: application/json

// {
//   "bulletin_id": "1",
//    "activite_id": "1",
//    "prenom": "test1",
 //   "ages": "1",
//    "poids": "1",
 //   "tailles": "1"
// }